# Generated by Django 5.0.7 on 2024-08-02 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='graphdata',
            index=models.Index(fields=['deleted_at'], name='api_graphda_deleted_c4caed_idx'),
        ),
        migrations.AddIndex(
            model_name='historicallog',
            index=models.Index(fields=['deleted_at'], name='api_histori_deleted_b2bfee_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['deleted_at'], name='api_mainten_deleted_491a97_idx'),
        ),
        migrations.AddIndex(
            model_name='mymodel',
            index=models.Index(fields=['name'], name='api_mymodel_name_791fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['deleted_at'], name='api_report_deleted_49f6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilemodel',
            index=models.Index(fields=['deleted_at'], name='api_userpro_deleted_554033_idx'),
        ),
    ]
