# Generated by Django 5.0.7 on 2024-07-16 12:39

import api.models.equipament_model
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('horimetro_inicialSuntech', models.FloatField(default=0, verbose_name='Ajuste de Zero Hora Suntech')),
                ('horimetro_inicialMaquina', models.FloatField(default=0, verbose_name='AZ Hora Máquina')),
                ('horimetro_total', models.FloatField(default=0, editable=False, verbose_name='Horímetro Total')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ano', models.IntegerField(blank=True, default=api.models.equipament_model.current_year, null=True, verbose_name='Ano')),
                ('numero_serie', models.CharField(max_length=255, unique=True, verbose_name='Número de Série')),
                ('modelo', models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='Modelo')),
                ('ponto_medicao', models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='Ponto de Medição')),
                ('combustivel', models.CharField(blank=True, default='DIESEL', max_length=8, null=True, verbose_name='Combustível')),
                ('numero_pulsos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de Pulsos')),
                ('perimetro_pneu', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Perímetro do Pneu (cm)')),
                ('horas_disponiveis_mes', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Horas Disponíveis por Mês')),
                ('consumo_medio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Consumo Médio (m³/h - L/h - Kg/h)')),
                ('alerta_velocidade', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Alerta de Velocidade (km/h)')),
                ('alerta_temperatura', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Alerta de Temperatura (°C)')),
                ('alerta_shock', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Alerta de Shock (km/h)')),
                ('horas_efetivas_hodometro', models.CharField(blank=True, default='HODOMETRO', max_length=255, null=True, verbose_name='Horas Efetivas ou Hodômetro')),
                ('hodometro', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hodômetro')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='api.device')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
                'indexes': [models.Index(fields=['device', 'nome'], name='api_equipam_device__137f7d_idx')],
            },
        ),
    ]
