# Generated by Django 5.0.7 on 2024-07-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
