# Generated by Django 5.0.7 on 2024-08-02 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_graphdata_api_graphda_deleted_c4caed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphdata',
            options={'verbose_name': 'Graph Data', 'verbose_name_plural': 'Graph Data'},
        ),
        migrations.AlterModelOptions(
            name='historicallog',
            options={'verbose_name': 'Historical Log', 'verbose_name_plural': 'Historical Logs'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveIndex(
            model_name='graphdata',
            name='api_graphda_deleted_c4caed_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicallog',
            name='api_histori_deleted_b2bfee_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='api_report_deleted_49f6ee_idx',
        ),
        migrations.AddIndex(
            model_name='graphdata',
            index=models.Index(fields=['device'], name='api_graphda_device__178fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='graphdata',
            index=models.Index(fields=['equipament'], name='api_graphda_equipam_696028_idx'),
        ),
        migrations.AddIndex(
            model_name='graphdata',
            index=models.Index(fields=['period'], name='api_graphda_period_43c3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='graphdata',
            index=models.Index(fields=['data_type'], name='api_graphda_data_ty_aa90a9_idx'),
        ),
        migrations.AddIndex(
            model_name='historicallog',
            index=models.Index(fields=['user'], name='api_histori_user_id_1e981c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicallog',
            index=models.Index(fields=['timestamp'], name='api_histori_timesta_5b8f80_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['start_date'], name='api_report_start_d_c62612_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['end_date'], name='api_report_end_dat_aaa824_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='api_report_report__50fbba_idx'),
        ),
    ]
