# Generated by Django 5.0.7 on 2024-07-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofilemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
