# Generated by Django 5.0.7 on 2024-07-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_graphdata_historicallog_maintenance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipament',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='api.device'),
        ),
    ]
