# Generated by Django 5.0.7 on 2024-08-02 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_maintenance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='userprofilemodel',
            name='api_userpro_deleted_554033_idx',
        ),
        migrations.AddIndex(
            model_name='userprofilemodel',
            index=models.Index(fields=['email'], name='api_userpro_email_278e94_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilemodel',
            index=models.Index(fields=['first_name', 'last_name'], name='api_userpro_first_n_bd1f81_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilemodel',
            index=models.Index(fields=['equipament'], name='api_userpro_equipam_510977_idx'),
        ),
    ]
