# Generated by Django 5.0.7 on 2024-08-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofilemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipament',
            old_name='begin_hour_device',
            new_name='initial_hour_device',
        ),
        migrations.RenameField(
            model_name='equipament',
            old_name='begin_hour_machine',
            new_name='initial_hour_machine',
        ),
    ]
