# Generated by Django 5.0.7 on 2024-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_device_deleted_by_equipament_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='alarm_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='usage_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
