# Generated by Django 5.0.7 on 2024-07-18 18:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='horimetro_inicial_peca',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
