# Generated by Django 5.0.7 on 2024-07-18 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_maintenance_horimetro_inicial_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='alarm_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='usage_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
