# Generated by Django 5.0.7 on 2024-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_maintenance_alarm_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='horimetro_inicial_peca',
            field=models.FloatField(default=0, verbose_name='AZ Hora Peça'),
        ),
    ]
