# Generated by Django 5.0.7 on 2024-07-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_maintenance_horimetro_inicialmaintenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='horimetro_inicial_peca',
        ),
    ]
